#!/usr/bin/env ruby

# for dev purposes
if ENV['SPIDR_CLI_GEM_DEV']
  puts '[WARN] spidr_cli loaded in development mode'
  require 'bundler/setup'
end

require 'spidr'
require 'spidr_cli/options'

require 'csv'
require 'optparse'

options = SpidrCLI::Options.new(ARGV)
start_at = options.url
header = options.header
columns = options.columns
content_types = options.content_types
spidr_method = options.spidr_method
spidr_options = options.spidr_options

start_at = options.url
if start_at.nil? || start_at.empty?
  puts options.usage_doc
  raise(ArgumentError, "<url> can't be blank")
end

# main
puts CSV.generate_line(columns) if header
Spidr.public_send(spidr_method, start_at, spidr_options) do |spider|
  spider.every_page do |page|
    next if content_types && content_types.all? { |type| !page.is_content_type?(type) }

    row = columns.map { |column| page.public_send(column) }
    puts CSV.generate_line(row)
  end
end
